//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntakeFIleProcessing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntakeFIleProcessing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [#TempCBIntake]
        ///(
        ///	[t_member_date] date NOT NULL,
        ///	[t_first_name] [varchar](30) NOT NULL,
        ///	[t_last_name] [varchar](30) NOT NULL,
        ///	[t_email] [varchar](60) NULL,
        ///	[t_phone] [varchar](15) NULL,
        ///	[t_address1] [varchar](35) NOT NULL,
        ///	[t_address2] [varchar](35) NULL,
        ///	[t_city] [varchar](23) NOT NULL,
        ///	[t_state] [varchar](35) NOT NULL,
        ///	[t_zip] [varchar](6) NOT NULL,
        ///	[t_country] [char](3) DEFAULT(&apos;USA&apos;) NOT NULL,
        ///	[t_dob] [date] NOT NULL,
        ///	[t_self_identify] int DEFAULT(1) NOT NULL,
        ///	[ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateTempIntake {
            get {
                return ResourceManager.GetString("CreateTempIntake", resourceCulture);
            }
        }
    }
}
